[default.general]
chip = "nrf52833_xxAA"

[default.reset]
enabled = true
halt_afterwards = false

[default.rtt]
enabled = true
log_enabled = true
log_path = "./logs"
timeout = 5000

[default.gdb]
enabled = false

[default.flashing]
enabled = true
